<template>
  <section class="governance-page"><header class="page-header"><div><p class="eyebrow">主管理员专属</p><h1 class="page-title">账号与权限</h1></div><button class="btn-primary" @click="showForm = !showForm">{{ showForm ? '收起表单' : '新建管理员' }}</button></header>
    <form v-if="showForm" class="card account-form" @submit.prevent="submit"><div class="form-grid"><label class="form-group">账号类型<select v-model="form.accountType" class="text-input"><option value="standalone">独立管理员账号</option><option value="classmate_linked">绑定已有同学账号</option></select></label><label class="form-group">显示名<input v-model.trim="form.displayName" class="text-input" /></label><label v-if="form.accountType === 'standalone'" class="form-group">用户名<input v-model.trim="form.username" class="text-input" /></label><label v-if="form.accountType === 'standalone'" class="form-group">初始密码<input v-model="form.initialPassword" type="password" class="text-input" /></label><label v-else class="form-group">绑定同学<select v-model="form.studentSlug" class="text-input"><option value="">请选择同学</option><option v-for="candidate in candidates" :key="candidate.slug" :value="candidate.slug">{{ candidate.name }}</option></select></label><label class="form-group">预设角色<select v-model="form.roleId" class="text-input"><option value="content_admin">内容管理员</option><option value="moderator">内容审核员</option><option value="operator">运营管理员</option></select></label></div><p class="form-hint">新建独立账号首次登录必须修改密码；绑定同学账号仅使用其同学登录会话。</p><p v-if="error" class="login-error">{{ error }}</p><button class="btn-primary" :disabled="saving">{{ saving ? '创建中...' : '创建管理员' }}</button></form>
    <div class="card table-card"><div v-if="loading">正在加载账号…</div><table v-else><thead><tr><th>管理员</th><th>登录方式</th><th>角色</th><th>状态</th><th>最近活动</th><th></th></tr></thead><tbody><tr v-for="account in accounts" :key="account.id"><td><strong>{{ account.displayName }}</strong><small>{{ account.username || account.studentSlug }}</small></td><td>{{ account.accountType === 'standalone' ? '独立账号' : '同学账号' }}</td><td>{{ roleLabel(account.roleId) }}</td><td><span :class="['status', account.status]">{{ account.status === 'active' ? '启用中' : '已停用' }}</span></td><td>{{ account.lastLoginAt || '尚未登录' }}</td><td><button v-if="account.canDisable && account.status === 'active'" class="btn-danger btn-sm" @click="disable(account)">停用</button></td></tr></tbody></table></div>
  </section>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import type { AdminAccountSummary } from '@alumni/shared'
import { createAdminAccount, disableAdminAccount, listAccountCandidates, listAdminAccounts } from '@/api/adminAccounts'
const accounts = ref<AdminAccountSummary[]>([]); const candidates = ref<Array<{ name: string; slug: string }>>([]); const loading = ref(true); const saving = ref(false); const showForm = ref(false); const error = ref('')
const form = reactive({ accountType: 'standalone' as 'standalone' | 'classmate_linked', displayName: '', username: '', initialPassword: '', studentSlug: '', roleId: 'moderator' as 'content_admin' | 'moderator' | 'operator' })
const roleLabel = (role: string) => ({ owner: '主管理员', content_admin: '内容管理员', moderator: '内容审核员', operator: '运营管理员' }[role] || role)
async function load() { loading.value = true; try { [accounts.value, candidates.value] = await Promise.all([listAdminAccounts(), listAccountCandidates()]) } finally { loading.value = false } }
async function submit() { saving.value = true; error.value = ''; try { await createAdminAccount({ ...form, permissionOverrides: [] }); showForm.value = false; form.displayName = ''; form.username = ''; form.initialPassword = ''; form.studentSlug = ''; await load() } catch (err: unknown) { error.value = err instanceof Error ? err.message : '创建失败' } finally { saving.value = false } }
async function disable(account: AdminAccountSummary) { if (!confirm(`确定停用“${account.displayName}”吗？其所有管理会话将立即失效。`)) return; await disableAdminAccount(account.id); await load() }
onMounted(load)
</script>
<style scoped>.governance-page{max-width:1100px}.eyebrow{font-size:12px;color:var(--color-muted);margin-bottom:4px}.account-form{margin-bottom:var(--spacing-lg)}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--spacing-sm)}.form-group{display:grid;gap:6px;font-size:13px}.form-hint{margin:8px 0 14px;color:var(--color-muted);font-size:13px}.table-card{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:13px 10px;border-bottom:1px solid var(--color-hairline);text-align:left;font-size:13px}th{color:var(--color-muted);font-weight:500}small{display:block;color:var(--color-muted);margin-top:3px}.status{font-weight:600}.status.active{color:var(--color-success)}.status.disabled{color:var(--color-error)}@media(max-width:680px){.form-grid{grid-template-columns:1fr}.table-card{padding:var(--spacing-sm)}th,td{white-space:nowrap}}</style>
