<template>
  <div class="admin-layout"><aside class="sidebar"><div class="sidebar-brand"><span class="brand-mark">✦</span><span class="brand-text">同学录管理</span></div><nav class="sidebar-nav"><router-link to="/dashboard" class="nav-item">工作台</router-link><p v-if="can('moderation.view')" class="nav-label">内容治理</p><router-link v-if="can('moderation.view')" to="/messages" class="nav-item">审核中心</router-link><p v-if="can('content.manage') || can('notifications.view') || can('notifications.publish')" class="nav-label">内容运营</p><router-link v-if="can('notifications.view') || can('notifications.publish')" to="/mail" class="nav-item">通知中心</router-link><router-link v-if="can('content.manage')" to="/albums" class="nav-item">相册管理</router-link><router-link v-if="can('content.manage')" to="/timeline" class="nav-item">时光轴</router-link><p v-if="isOwner" class="nav-label">主管理员</p><router-link v-if="can('students.manage')" to="/students" class="nav-item">学生管理</router-link><router-link v-if="can('site.settings.manage')" to="/settings" class="nav-item">站点设置</router-link><router-link v-if="can('admins.manage')" to="/accounts" class="nav-item">账号与权限</router-link><router-link v-if="can('audit.view')" to="/audit-logs" class="nav-item">操作日志</router-link></nav><div class="sidebar-footer"><span class="identity">{{ admin?.displayName || '管理员' }}</span><button class="logout-btn" @click="handleLogout">退出登录</button></div></aside><main class="admin-main"><router-view /></main></div>
</template>
<script setup lang="ts">
import { computed } from 'vue'
import type { AdminPermission } from '@alumni/shared'
import { adminLogout, getCurrentAdmin } from '@/api/client'
const admin = computed(() => getCurrentAdmin())
const isOwner = computed(() => !!admin.value?.isOwner)
function can(permission: AdminPermission) { return !!admin.value && (admin.value.isOwner || admin.value.permissions.includes(permission)) }
async function handleLogout() { await adminLogout() }
</script>
<style scoped>.admin-layout{display:flex;min-height:100vh}.sidebar{width:240px;background:var(--color-surface-dark);color:var(--color-on-dark);display:flex;flex-direction:column;flex-shrink:0}.sidebar-brand{padding:22px 20px;border-bottom:1px solid var(--color-surface-dark-elevated)}.brand-mark{color:var(--color-primary);margin-right:8px}.brand-text{font-family:var(--font-display);font-size:18px}.sidebar-nav{flex:1;padding:12px;display:flex;flex-direction:column;gap:3px}.nav-label{margin:15px 9px 4px;color:var(--color-on-dark-soft);font-size:10px;letter-spacing:.08em}.nav-item{padding:10px 12px;border-radius:var(--rounded-md);color:var(--color-on-dark-soft);font-size:14px}.nav-item:hover,.nav-item.router-link-active{background:var(--color-surface-dark-elevated);color:var(--color-on-dark);text-decoration:none}.sidebar-footer{padding:14px;border-top:1px solid var(--color-surface-dark-elevated)}.identity{display:block;color:var(--color-on-dark-soft);font-size:12px;margin:0 4px 8px}.logout-btn{width:100%;padding:8px;color:var(--color-on-dark-soft);border-radius:var(--rounded-md)}.admin-main{flex:1;padding:var(--spacing-xl);overflow-y:auto}@media(max-width:768px){.admin-layout{display:block;padding-bottom:66px}.sidebar{position:fixed;z-index:20;bottom:0;left:0;width:100%;height:62px;display:block}.sidebar-brand,.nav-label,.sidebar-footer{display:none}.sidebar-nav{height:62px;padding:6px;overflow-x:auto;flex-direction:row;gap:4px}.nav-item{white-space:nowrap;padding:10px}.admin-main{padding:var(--spacing-lg)}}</style>
